name: Run Gosec and ZAP Scan
on:
  workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image
        run: |
          docker build -t juice-shop:${{github.sha}} .
      - name: GitLeaks
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.REPOTOKEN }}
