name: Run Gosec and ZAP Scan
on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: GitLeaks
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
